### ISSUE TITLE
Код ошибки исполнения ZFE_Console_Command

### ISSUE THREAD

**Issue by Dezzpil** [zfbase/zfe#22]
Добавить возможность при исключении ZFE_Console_Exception выйти с произвольным кодом, указанным в брошенном исключении (которое обязано быть > 0)

zfe/bin/zfe-tools
![изображение](https://user-images.githubusercontent.com/845600/70155379-344b3800-16c3-11ea-85c6-a894d19793b5.png)

**Comment by IlyaSerdyuk** [comment]
Добавлено в 1.35.0-beta.8
