### ISSUE TITLE
Исправить тип в @return метода setHard()

### ISSUE THREAD

**Issue by Dezzpil** [zfbase/zfe#23]
Сейчас возвращает bool, чем ломает автодополнение при цепочке вызовов
![изображение](https://user-images.githubusercontent.com/845600/70163516-ad9d5780-16d0-11ea-97e0-4fdc41e3c83d.png)

**Comment by IlyaSerdyuk** [comment]
Исправлено в версиях:
1.35.0-beta.7
1.34.8
1.33.112
