### ISSUE TITLE
Заменить id пользователя CLI на логин

### ISSUE THREAD

**Issue by Dezzpil** [zfbase/zfe#37]
https://github.com/zfbase/zfe/blob/742fac35a7e4e7b461b7b24b4c2336a944b28c56/library/ZFE/Bootstrap.php#L168

**Comment by IlyaSerdyuk** [comment]
С версии 1.35.0-beta.8 можно указывать как ID пользователя CLI, так и логин.
Если указать одновременно ID и логин будет использоваться ID.
